### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RaviTejaCMS**
Updated TOR Android "tor-browser-mobile-window"  Screenshots(only png)
#DocsHackathon
#MyFirstPullrequest

### CODE REVIEW

**Comment by mpguerra** [comment]
I'm missing the context for this change, which issue is this solving?

**Comment by gusgustavo** [comment]
It solves this one: https://dip.torproject.org/web/tpo/issues/30

**Comment by mpguerra** [comment]
got it, will merge now

**Comment by mpguerra** [comment]
e40ebe9c354e3c7e76b859935fc41d212178ba6e cherry-picked to master

**Pull request closed without merging**
