### PR TITLE
Updated links on /press

### PR DESCRIPTION
**Pull request by gaelletjat**
Updated all the links I was able to find from either the new url or Wayback machine.
Missing about 15. Among them some from the Tor blog where I opened issues on GitLab. 
Please advise.
Thank you

### CODE REVIEW

**Comment by emmapeel2** [comment]
> Updated all the links I was able to find from either the new url or Wayback machine.
> Missing about 15. Among them some from the Tor blog where I opened issues on GitLab.

I don't think it is needed to delete the broken link mentions. Maybe you can add a link saying 'unavailable' or similar?

Another thing: maybe all the available ones should be saved on the WaybackMachine, so we make sure we are not going to lose them? (thanks arma for hint)

**Comment by gaelletjat** [comment]
I will correct that this week.
Thank you very much for your invaluable feedbacks @emmapeel2

**Comment by stephanieawhited** [comment]
Great, thanks for doing this!

**Comment by emmapeel2** [comment]
this was merged a while ago, also @hiromipaw found an idea about non active links.
not sure why it does not appear merged, but i think this can be closed, if possible 'merged somehow'

**Review by gusgustavo — APPROVED** [review]

**Comment by gusgustavo** [comment]
I don't think this PR was merged, @emmapeel2. 
But I just reviewed all the links today, and I can merge tomorrow.

**Pull request merged**
